### ISSUE TITLE
OOPS_BACKPLANE_OUTPUT_PATH should not be required

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-oops#38]
Currently the environment variable OOPS_BACKPLANE_OUTPUT_PATH must be set, even if you aren't storing new backplanes. The environment variable should not be required in that case (e.g. on test runners).

If it isn't set, you get:

```
ERROR: runTest (oops.backplane.Test_Backplane_Exercises.runTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/testrunner/tests/oops/src/pds-oops/oops/backplane/__init__.py", line 1092, in runTest
    exercise_backplanes(obs, use_inventory=True, inventory_border=4,
  File "/home/testrunner/tests/oops/src/pds-oops/oops/backplane/exercise_backplanes.py", line 255, in exercise_backplanes
    exercise_backplanes_settings(obs)
  File "/home/testrunner/tests/oops/src/pds-oops/oops/backplane/exercise_backplanes.py", line 237, in exercise_backplanes_settings
    os.path.join(os.environ['OOPS_BACKPLANE_OUTPUT_PATH'], specdir)
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'OOPS_BACKPLANE_OUTPUT_PATH'
```

**Comment by rfrenchseti** [comment]
This is already fixed
