### ISSUE TITLE
Hosts unit tests pass even with critical missing environment variable

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-oops#69]
If the `OOPS_RESOURCES` and `OOPS_TEST_DATA_PATH` environment variables are not defined, the hosts tests give a critical error, but then still mark themselves as passing. Mark attempted to fix this in https://github.com/SETI/pds-oops/pull/61 but apparently it didn't work.

**Comment by rfrenchseti** [comment]
This appears to actually work as expected now.

```
Traceback (most recent call last):
  File "/seti/oops/rms-oops/oops/hosts/galileo/ssi/__init__.py", line 295, in test_C0374685140R
    gm.execute_as_unittest(self, 'C0374685140R')
  File "/seti/oops/rms-oops/oops/backplane/gold_master.py", line 625, in execute_as_unittest
    testcase.assertTrue(False, str(e))
AssertionError: False is not true : Undefined environment variable: One of OOPS_TEST_DATA_PATH or OOPS_RESOURCES must be provided

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
```
